steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy synapse \
      --source . \
      --region us-east1 \
      --project gen-lang-client-0479504041
